# NumPy Array Indexing

In [3]:
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[:5]=100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr=np.arange(0,11)

In [12]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr=arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy=arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:]=100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2d Array indexing

In [26]:
my_arr=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
my_arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
my_arr[1][2]

30

In [31]:
my_arr[2]

array([35, 40, 45])

In [33]:
#recommended
my_arr[1,2]

30

In [34]:
my_arr[2,1]

40

In [35]:
#grabbing a portion of the matrix
my_arr[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
my_arr[1:,]

array([[20, 25, 30],
       [35, 40, 45]])

In [37]:
my_arr[1:,:2]

array([[20, 25],
       [35, 40]])

In [38]:
#conditional
arr_1d=np.arange(0,11)

In [39]:
bool_arr=arr_1d>5

In [40]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [41]:
arr_1d[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr_1d[arr_1d>5]

array([ 6,  7,  8,  9, 10])

In [51]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
arr_2d[2:4,5:7]

array([[25, 26],
       [35, 36]])