In [7]:
import numpy as np
mylist=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#np.linspace(start,end,total number between start and end)
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#random function unifrom distribution

#random number between 0 and 1 in 1d
np.random.rand(5)

array([0.71800828, 0.41844554, 0.74375708, 0.07175943, 0.0336067 ])

In [28]:
#random number between 0 and 1 in 2d
np.random.rand(5,5)

array([[0.45601201, 0.70946427, 0.68120536, 0.65249633, 0.28476141],
       [0.50391455, 0.93375475, 0.01567448, 0.89523392, 0.04593943],
       [0.06613901, 0.77795269, 0.05863419, 0.81657676, 0.4458694 ],
       [0.4685683 , 0.98288792, 0.2114834 , 0.78454918, 0.82179826],
       [0.08117989, 0.40168707, 0.17713854, 0.83591657, 0.51550288]])

In [29]:
#random number standard normal distribution
np.random.randn(5)

array([-1.63401192,  0.14824991, -0.26570356, -0.93317696, -0.46497257])

In [33]:
#random integer numbers
#np.random.randint(low,high,total number)
#inclusive in the low end and exclusive in the high end
np.random.randint(0,10,100)

array([0, 5, 9, 7, 9, 7, 9, 9, 8, 4, 4, 9, 3, 2, 8, 4, 0, 3, 0, 7, 6, 3,
       2, 4, 8, 0, 8, 8, 4, 5, 0, 2, 1, 9, 7, 5, 2, 3, 9, 0, 0, 1, 4, 7,
       7, 0, 6, 6, 1, 6, 1, 0, 6, 0, 8, 4, 5, 7, 5, 7, 0, 3, 5, 0, 0, 1,
       3, 6, 0, 1, 3, 1, 5, 3, 1, 9, 1, 6, 0, 8, 4, 6, 2, 3, 7, 1, 9, 5,
       1, 6, 3, 6, 2, 6, 2, 3, 2, 3, 3, 6])

In [37]:
#reshape
arr=np.arange(25)
arr
#total element need to be equal row*column
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
array=np.random.randint(0,20,10)
print(array)
array.max()

[ 9 12 19 10  7  3  3 12 17  1]


19

In [56]:
array.min()

1

In [60]:
#index location of max and min
print(array.argmax())
print(array.argmin())
#shape
array.shape




2
9


(10,)

In [61]:
#data type
array.dtype

dtype('int32')